'''
	keywords_to_text.py

	https://medium.com/mlearning-ai/generating-sentences-from-keywords-using-transformers-in-nlp-e89f4de5cf6b#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjcxM2ZkNjhjOTY2ZTI5MzgwOTgxZWRjMDE2NGEyZjZjMDZjNTcwMmEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2Njg0MjQzNjIsImF1ZCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwMTU1NTQ5MTgwMzc4MDk4ODMzNSIsImVtYWlsIjoiY2FybG9zLmFndWlsYXIucGFsYWNpb3NAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsIm5hbWUiOiJDYXJsb3MgQWd1aWxhciIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BTG01d3UxZTY5SmF6Y1pZQ1BPbXg0RnJNaXZ6bU5LWUNMVzJ6cF9KTUFyNXBnPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6IkNhcmxvcyIsImZhbWlseV9uYW1lIjoiQWd1aWxhciIsImlhdCI6MTY2ODQyNDY2MiwiZXhwIjoxNjY4NDI4MjYyLCJqdGkiOiIzNWZhNzhlOTZmNGM1MWIwOTVkYWMzMDAxMWQ3MWE1ODgyM2M5ZmU0In0.HS_qfA0Gj2zoeLSP-ZhQ4cSoizsU6D408kAj6H_XE58qTwzKfBvCN4UWJkOULRI_SC7zQiOE-cRi7AXFIexiQWzbSYHEWM3xmgKSEypCfsxGpjRyzlgD71jJGUzt3ifKTiF3MuD5whEkNYey5hUkWRIMLL7c3_xKDpWBxSyXdtSotMBqn8pt2X8X-dGSL52c_KmHGkryV1Z0f5dJmxQGU-m-WslH3KnApn5PO9WM_tbJnsFKwHb2PGPonBs8zJNnrMqV5HU5d-gaF-HGJ5QpwrMcEpQeOc-fuHX5MAkPsiFa1UE9DAq1UQ0gDuwUI6Ni50TjNhAfLj3IhU-8LtFBaw

	pip3 install keytotext

	https://github.com/gagan3012/keytotext

'''


from keytotext import pipeline
nlp = pipeline("k2t-base")  #loading the pre-trained model
params = {"do_sample":True, "num_beams":4, "no_repeat_ngram_size":3, "early_stopping":True}    #decoding params


gen_text = nlp(['student', 'phrasal_verbs', 'practice', 'fluency'], **params)
print(gen_text)  #keywords